# Name of component under test
COMPONENT_NAME = component-name

include ../../flubber/cpputest-config

# Includes (.hpp) for this component
INCLUDE_DIRS += \
# $(PROJECT_DIR)/include/ \
# $(PROJECT_DIR)/unit-tests/mocks/include/

# Source files (.cpp) for this component
SRC_FILES = \
# $(PROJECT_DIR)/source/some-file.cpp

# Run MakefileWorker.mk with the variables set in this Makefile
include $(CPPUTEST_HOME)/build/MakefileWorker.mk
